### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by MarcinusX** [Fidev-io/framy#10]
Show all screens in one page

**Comment by kg551915** [comment]
You know what would be super awesome, if Framy automatically displayed only screens that contain errors based on preset data. Such that, 'Okay, iPhone X overflows on WidgetX using PresetX'.  

So that instead of having to manually walk-through all devices and all presets, Framy can just show you the information you care about. Allowing developers to quickly see where they need to go to focus their energy and time. Personally, such a feature would save even more time (on top of what Framy is already offering) and be invaluable to developers.

**Comment by MarcinusX** [comment]
@kg551915 That is a neat idea! I would add it as another issue though :)
